SearchForm 개선
namu-theseed/theseed-skin-liberty pull request #63
Opened 2022-11-26 06:46 UTC by Fakeness

버그만 없으면 마지막 PR일 것 같습니다.

2022-11-26 08:18 UTC, Tenpower commented
#64 같이 해결 바랄께요.

2022-11-26 16:28 UTC, namu-theseed requested changes

2022-11-26 17:07 UTC, Fakeness commented
변경했습니다.

2022-11-26 17:17 UTC, Fakeness commented on layout.vue
> +                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" @click="$store.state.localConfig['wiki.hide_user_document_discuss'] = $store.state.session.member.u
혹시 이 부분은 문제 없나요?

2022-11-26 17:38 UTC, namu-theseed commented on layout.vue
> +                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" @click="$store.state.localConfig['wiki.hide_user_document_discuss'] = $store.state.session.member.u
```@close="$store.commit('localConfigSetValue', {key: 'wiki.hide_user_document_discuss', value: $store.state.session.member.user_document_discuss})"```

2022-11-26 17:45 UTC, Fakeness commented
변경했습니다.

2022-11-27 08:49 UTC, merged

2022-11-27 09:11 UTC, Fakeness commented
@namu-theseed searchForm.vue에 $store가 정의되어 있지 않은 것 같습니다.
import Setting from '~/components/setting';
해당 부분에 정의되어 있을 것 같기는 한데 추가하면 될까요?